[package]
name = "polydb-db-sqlite"
version.workspace = true
edition.workspace = true
description = "PolyDB SQLite driver"

[dependencies]
polydb-core = { workspace = true }
polydb-protocol = { workspace = true }
polydb-db-core = { workspace = true }
async-trait = { workspace = true }
thiserror = { workspace = true }
rusqlite = { workspace = true }
parking_lot = { workspace = true }
serde_json = { workspace = true }

[dev-dependencies]
smol = { workspace = true }
